[package]
name = "darth-rust"
version = "0.2.0"
edition = "2021"
description = "Darth rust"
authors = ["Pas2Rust <pas2000@proton.me>"]
license = "MIT"

[dependencies]
bcrypt = "*"
chrono = "*"
colorful = "*"
jsonwebtoken = "*"
lazy_static = "*"
proc-macro2 = "*"
quote = "*"
rand = "*"
serde = "*"
serde-xml-rs = "*"
serde_json = "*"
serde_yaml = "*"
syn = {version = "*", features = ["full"]}
tokio = "*"
toml = "*"

[dependencies.uuid]
version = "*"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[lib]
proc-macro = true
path = "src/lib.rs"
