[package]
name = "darth-rust"
version = "0.1.0"
edition = "2021"
description = "Darth rust"
authors = ["Pas2Rust <pas2000@proton.me>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
colorful = "0.2.2"
lazy_static = "1.4.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
serde = "1.0.190"
serde-xml-rs = "0.6.0"
serde_json = "1.0.108"
serde_yaml = "0.9.27"
syn = {version = "2.0.38", features = ["full"] }
tokio = "1.33.0"
toml = "0.8.6"

[lib]
proc-macro = true
path = "src/lib.rs"
