[package]
name = "darth-rust"
version = "0.2.5"
edition = "2021"
description = "Darth rust"
authors = ["Pas2Rust <pas2000@proton.me>"]
homepage = "https://github.com/pas2rust/darth-rust"
repository = "https://github.com/pas2rust/darth-rust"
license = "MIT"

[package.metadata.docs.rs]
logo-url = "https://i.imgur.com/svdzGva.jpg"

[dependencies]
argon2 = "0.5.2"
bcrypt = "^0.15.0"
chrono = "^0.4.31"
colorful = "^0.2.2"
jsonwebtoken = "^9.1.0"
lettre = "^0.11.1"
mongodb = "2.7.1"
proc-macro2 = "^1.0.69"
quote = "^1.0.33"
rand = "^0.8.5"
serde = "^1.0.190"
serde_json = "^1.0.108"
syn = {version = "^2.0.38", features = ["full"]}

[dependencies.uuid]
version = "^1.5.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[lib]
proc-macro = true
path = "src/lib.rs"

